[tox]
isolated_build = true
envlist =
    py39-django42
    py310-django50
    py312-django51
    py313-django52
    py314-django60
    ruff

[testenv]
deps =
    django42: Django>=4.2,<4.3
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    django42: cx-Oracle
    django50, django51, django52, django60: oracledb
    mysqlclient
    psycopg2-binary
commands =
    python -W error::ResourceWarning -W error::DeprecationWarning -W error::PendingDeprecationWarning -m django test --settings=tests.sqlite_settings
    python -W error::ResourceWarning -W error::DeprecationWarning -W error::PendingDeprecationWarning -m django test --settings=tests.postgresql_settings
    python -W error::ResourceWarning -W error::DeprecationWarning -W error::PendingDeprecationWarning -m django test --settings=tests.mysql_settings
    python -W error::ResourceWarning -W error::DeprecationWarning -W error::PendingDeprecationWarning -m django test --settings=tests.oracle_settings
passenv =
    SEQUENCES_*

[testenv:ruff]
commands =
    ruff format --check src tests
    ruff check src tests
deps =
    ruff
